"""
Django settings for inventory project.
Generated by 'django-admin startproject' using Django 4.2.27.
"""
import os
import sys
import time
import socket
import logging
from pathlib import Path
from datetime import timedelta
import pymysql
import dj_database_url

# ==================== CRITICAL: EARLY VARIABLE CHECK ====================
print("🚀 STARTING DJANGO - Checking Environment Variables")

# Small delay to ensure Railway injects variables
time.sleep(1)

# Check ALL MySQL variables
mysql_vars = ['MYSQLHOST', 'MYSQLPORT', 'MYSQLUSER', 'MYSQLDATABASE', 'MYSQLPASSWORD']
for var in mysql_vars:
    value = os.environ.get(var)
    if value is None:
        print(f"❌ {var}: NOT FOUND")
    elif value.strip() == '':
        print(f"⚠️  {var}: EMPTY")
    else:
        # Show first/last few chars for passwords
        if 'PASSWORD' in var and value:
            print(f"✅ {var}: '{value[:3]}...{value[-3:]}' (length: {len(value)})")
        else:
            print(f"✅ {var}: '{value}'")

# Check if MYSQLHOST resolves
mysql_host = os.environ.get('MYSQLHOST', '').strip()
if mysql_host:
    try:
        print(f"🔍 Testing DNS: {mysql_host}")
        ip = socket.gethostbyname(mysql_host)
        print(f"✅ DNS resolved to: {ip}")
    except socket.gaierror as e:
        print(f"❌ DNS FAILED: {e}")
        print("This means 'mysql.railway.internal' cannot be found")
else:
    print("❌ MYSQLHOST is empty!")

print("=" * 60)

# Exit if critical variables missing
required = ['MYSQLHOST', 'MYSQLUSER', 'MYSQLPASSWORD']
missing = [var for var in required if not os.environ.get(var)]
if missing:
    print(f"💥 CRITICAL: Missing {missing}")
    print("Available MySQL vars:")
    for key in sorted(os.environ.keys()):
        if 'MYSQL' in key.upper():
            print(f"  {key}: {os.environ.get(key)}")
    # sys.exit(1)  # Uncomment to fail fast

pymysql.install_as_MySQLdb()
logger = logging.getLogger(__name__)

SECRET_KEY = os.environ.get("SECRET_KEY", "unsafe-dev-key")

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

BASE_DIR = Path(__file__).resolve().parent.parent
DEBUG = False
ALLOWED_HOSTS = ["*"]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products',
    'accounts',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

ROOT_URLCONF = 'inventory.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventory.wsgi.application'

# ==================== DATABASE CONFIGURATION ====================
print("⚙️ Configuring Database...")

# Clean all values
def clean_env(var_name, default=''):
    value = os.environ.get(var_name, default)
    if value:
        return value.strip().strip('"\'')
    return default

mysql_host = clean_env('MYSQLHOST')
mysql_port = clean_env('MYSQLPORT', '3306')
mysql_db = clean_env('MYSQLDATABASE', 'railway')
mysql_user = clean_env('MYSQLUSER', 'root')
mysql_password = clean_env('MYSQLPASSWORD')

print(f"📦 Final DB Config:")
print(f"   Host: {mysql_host}")
print(f"   Port: {mysql_port}")
print(f"   DB: {mysql_db}")
print(f"   User: {mysql_user}")
print(f"   Password: {'***' if mysql_password else 'MISSING'}")

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': mysql_host,
        'PORT': mysql_port,
        'NAME': mysql_db,
        'USER': mysql_user,
        'PASSWORD': mysql_password,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'connect_timeout': 30,
            'read_timeout': 30,
            'write_timeout': 30,
        },
        'CONN_MAX_AGE': 600,
    }
}

# Test connection immediately
try:
    print("🔗 Testing database connection...")
    from django.db import connections
    conn = connections['default']
    conn.ensure_connection()
    print("✅ Database connection SUCCESSFUL!")
except Exception as e:
    print(f"❌ Database connection FAILED: {e}")
    print("Troubleshooting steps:")
    print("1. Check MySQL service is running in Railway")
    print("2. Verify variables in backend service")
    print("3. Check if services are connected in Railway")

print("=" * 60)
# ==================== END DATABASE CONFIG ====================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOW_ALL_ORIGINS = True